<a href="https://colab.research.google.com/github/Sripathm2/UCLA_CS_245_Project5/blob/main/Clean_Data/County_Data_Builder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%pip install pandas

In [25]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [26]:
%cd /content/drive/MyDrive/CS245

/content/drive/MyDrive/CS245


In [27]:
import pandas as pd
sci = pd.read_csv('/content/drive/MyDrive/CS245/county_county_aug2020.tsv', sep='\t').values
fips = sci[:3229][:,1].tolist()

In [28]:
import numpy as np
adj = np.zeros((3229,3229))
for i in range(3229):
  end_idx = (i+1)*3229
  start_idx = i*3229
  sci_i = sci[start_idx:end_idx]
  adj[i] = sci_i[:,2]

In [29]:
covid = pd.read_csv('/content/drive/MyDrive/CS245/Clean_us-counties.csv', sep=',').values

In [43]:
data_length = np.zeros(3229)
for i in range(covid.shape[0]):
  for fip in fips:
    if covid[i,1] == fip:
      idx = fips.index(fip)
      data_length[idx] += 1

In [45]:
seq_max = np.amin(data_length)
print(data_length)

[258. 268. 248. ... 245. 245. 245.]


In [31]:
# Convert dates to numbers
for i in range(covid.shape[0]):
  d = covid[i,0]
  n = date[d]
  covid[i,0] = n

In [18]:
X = np.zeros([321,3229,5])
y = np.zeros([321,3229,1])
window = 6

for i in range(X.shape[0]):
   for j in range(X.shape[1]):
     

In [23]:
# Build date dictionary
date = {}
k = 1
for i in range(1,13):
  if i == 1:
    for j in range(21,32):
      date_str = str(i)+'/'+str(j)+'/2020'
      date[date_str] = k
      k += 1
  if i == 2:
    for j in range(1,30):
      date_str = str(i)+'/'+str(j)+'/2020'
      date[date_str] = k
      k += 1
  if i == 3 or i == 5 or i == 7 or i == 8 or i == 10:
    for j in range(1,32):
      date_str = str(i)+'/'+str(j)+'/2020'
      date[date_str] = k
      k += 1
  if i == 4 or i == 6 or i == 9 or i == 11:
    for j in range(1,31):
      date_str = str(i)+'/'+str(j)+'/2020'
      date[date_str] = k
      k += 1
  if i == 12:
    for j in range(1,7):
      date_str = str(i)+'/'+str(j)+'/2020'
      date[date_str] = k
      k += 1


In [119]:
data_idx = np.copy(data_length)
for i in range(3229):
  if i == 0:
    pass
  else:
    data_idx[i] += data_idx[i-1]
data_idx = data_idx.astype(np.int64)

In [131]:
covid_pad = np.zeros([321*3229,3])
for i in range(3229):
  if i == 0:
    covid_pad[covid[0,0]:(i+1)*321+1] = covid[i:data_idx[i]]
  else:
    print(i)
    d = covid[data_idx[i-1]:data_idx[i]]
    if d.shape != (0,3):
      covid_pad[321*i+covid[data_idx[i-1],0]:(i+1)*321+1] = d

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277


ValueError: ignored

In [135]:
i = 566
print(data_idx[i-1])
print(data_idx[i])
print(covid[data_idx[i-1]:data_idx[i]].shape)
covid_pad[321*i+covid[data_idx[i-1],0]:(i+1)*321+1].shape

143814
143949
(135, 3)


(141, 3)

In [121]:
for i in range(74,77):
  print(covid[data_idx[i]])

[141 2100 1]
[63 2110 1]
[63 2110 1]


In [124]:
for i in range(70,80):
  print(data_idx[i])

18152
18343
18508
18698
18964
19145
19145
19404
19668
19933


In [125]:
for i in range(70,80):
  print(data_length[i])

244.0
191.0
165.0
190.0
266.0
181.0
0.0
259.0
264.0
265.0
